apiVersion: v1
kind: ReplicationController
metadata:
  name: autoscaler
spec:
  replicas: 1
  selector:
    app: autoscaler
  template:
    metadata:
      labels:
        app: autoscaler
        openai/do-not-drain: "true"
    spec:
      containers:
      - name: autoscaler
        image: wbuchwalter/autoscaler
        env:
        - name: AZURE_SP_APP_ID
          valueFrom:
            secretKeyRef:
              name: autoscaler
              key: azure-sp-app-id
        - name: AZURE_SP_SECRET
          valueFrom:
            secretKeyRef:
              name: autoscaler
              key: azure-sp-secret
        - name: AZURE_SP_TENANT_ID
          valueFrom:
            secretKeyRef:
              name: autoscaler
              key: azure-sp-tenant-id       
        - name: PYKUBE_KUBERNETES_SERVICE_HOST
          value: 10.240.255.15
          # value: kubernetes.default
        - name: DATADOG_TAGS
          value: env:sci
        command:
            - python
            - main.py
            - --resource-group 
            - cluster
            - --sleep
            - "20"
            - --debug           
            - -vvv
            - --over-provision
            - "0"
            - --template-file-url
            - https://gist.githubusercontent.com/wbuchwalter/5f52a563f7f7f52416f55e82dcd6b290/raw/c6340c1f6ac794af2648bc136989aba28bd76c37/template.json
            - --parameters-file-url
            - https://gist.githubusercontent.com/wbuchwalter/a8a3076f4ece7ec05fff1a82f4779224/raw/63323c28222c07b0a70a3fee93b06da9559393f8/params.json
        imagePullPolicy: Always
      restartPolicy: Always
      dnsPolicy: Default  # Don't use cluster DNS.
