apiVersion: v1
kind: ReplicationController
metadata:
  name: autoscaler
spec:
  replicas: 1
  selector:
    app: autoscaler
  template:
    metadata:
      labels:
        app: autoscaler
        openai/do-not-drain: "true"
    spec:
      containers:
      - name: autoscaler
        image: wbuchwalter/autoscaler
        env:
        - name: AZURE_SP_APP_ID
          valueFrom:
            secretKeyRef:
              name: autoscaler
              key: azure-sp-app-id
        - name: AZURE_SP_SECRET
          valueFrom:
            secretKeyRef:
              name: autoscaler
              key: azure-sp-secret
        - name: AZURE_SP_TENANT_ID
          valueFrom:
            secretKeyRef:
              name: autoscaler
              key: azure-sp-tenant-id       
        - name: PYKUBE_KUBERNETES_SERVICE_HOST
          value: 10.240.255.15
          # value: kubernetes.default
        - name: DATADOG_TAGS
          value: env:sci
        command:
            - python
            - main.py
            - --resource-group 
            - acs
            - --container-service-name 
            - containerservice-acs            
            - -vvv
            - --over-provision
            - "0"
        imagePullPolicy: Always
      restartPolicy: Always
      dnsPolicy: Default  # Don't use cluster DNS.
